add HTML template file for opening links in new tab
camunda/camunda-docs-theme pull request #12
Opened 2020-11-09 21:49 UTC by akeller

When clicking a URL, the URL will open in a new tab. I confirmed this functionality with the URLs in Get Started > Quickstart content.

This HTML template appears to work for all links except links inside notes.

2020-11-09 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-theme?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-theme?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-theme?pullRequest=12) it.</sub>

2020-11-11 11:08 UTC, koevskinikola commented
@marstamm or @tasso94 can you have a look at this?

2020-11-12 08:22 UTC, marstamm requested changes
Hi @akeller ,

thanks for opening the PR. Unfortunately this won't work on the live version of the docs, which are build using hugo v0.54.0. The [Markdown render hooks](https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks) are only available starting in v0.62.0.

AFAIK, the hugo version was chosen on purpose, but don't know the details. An update would probably require a larger effort.

I'm not sure if we can achieve this behavior in 0.54 as well.

Cheers
Martin

2020-11-12 15:00 UTC, akeller commented
Hi @marstamm,

Thanks for the info. I'll start an email thread internally to identify all the players and to see what it would take to understand level of effort to update to a newer version of Hugo. I see the latest version is v0.78. 

To me this is a critical UX issue and anti pattern to have links not open in a separate tab. 

Thanks,
Amara

2020-11-13 07:59 UTC, ingorichtsmeier commented
Hi @akeller,

we consultants use the same theme for our training exercises. I've added 

```
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
```

to the `config.yaml` to open the links in new windows. That works with hugo 0.54.

Cheers, Ingo

2022-07-01 21:57 UTC, closed without merging